config/routes.rb
Rails.application.routes.draw do
  resources :photos
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "events#index"
    devise_for :users

    resources :preferences, only: [:update]
    resources :events do
      resources :comments, only: [:create, :destroy]
      resources :subscriptions, only: [:create, :destroy]
      resources :photos, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update]
  end
end

app/models/user.rb
class User < ApplicationRecord
  EMAIL_ADDRESS = /\A[a-zA-Z0-9\-_.]+@[a-zA-Z0-9\-_.]+\z/
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_one :preference, dependent: :destroy

  before_validation :set_name, on: :create

  validates :name, presence: true, length: { maximum: 35 }

  validates :email,
            length: { maximum: 255 },
            uniqueness: true,
            format: EMAIL_ADDRESS

  after_commit :link_subscriptions, :set_profile, on: :create
  mount_uploader :avatar, AvatarUploader

  private

  def link_subscriptions
    Subscription.where(user_id: nil, user_email: self.email).update_all(user_id: self.id)
  end

  def set_name
    self.name = "Anonymous №#{rand(777)}" if self.name.blank?
  end

  def set_profile
    Preference.create(user_id: self.id, payload: {theme: '#060c22', locale: 'en'})
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Встроенный в девайз фильтр — посылает незалогиненного пользователя
  before_action :authenticate_user!, except: [:show]

  # Задаем объект @user для шаблонов и экшенов
  before_action :set_current_user, except: [:show]

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: I18n.t('controllers.users.updated')
    else
      render :edit
    end
  end

  private

  def set_current_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :email, :avatar)
  end
end

app/views/users/_form.html.erb
<%= form_for @user, html: { multipart: true } do |f| %>
  <%= render partial: 'partials/form_errors', locals: { model: @user } %>
  <div class="mb-3">
    <%= f.text_field :name, class: 'form-control', placeholder: 'Your name' %>
  </div>
  <div class="mb-3">
    <%= f.text_field :email, class: 'form-control', placeholder: 'Your email' %>
  </div>
  <div class="mb-3">
    <p><%= image_tag(@user.avatar.thumb.url) if @user.avatar? %></p>
    <%= f.file_field :avatar, placeholder: 'Upload your avatar' %>
  </div>
  <div class="mb-3">
    <%= f.submit "Update", class: "form-button text-center" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<%= image_tag(user_avatar_thumb(user), class: 'img-icon') %>
<% if request.path == user_path(user) %>
  <%= user.name %>
<% else %>
  <%= link_to user.name, user_path(user) %>
<% end %>

app/views/users/edit.html.erb
<% content_for :title do %>Edit Profile <%= @user.name %>
<% end %>
<div class="container px-4 p-5">
  <div class="row text-center">
    <div class="col gx-0"></div>
    <div class="col-md-6">
      <div class="section-header">
        <h2>Editing Profile</h2>
        <% if @user == current_user %>
          <%= link_to 'Back', :back %>
        <% end %>
      </div>
      <%= render 'form' %><br>
      <p><%= link_to 'Change password / Delete account', edit_user_registration_path %></p>
      <%= render partial: 'preferences/form' %>
    </div>
    <div class="col"></div>
  </div>
</div>

app/views/users/show.html.erb
<% content_for :title do %>Profile <%= @user.name %>
<% end %>
<div class="container px-4 p-5 text-center">
  <div class="section-header">
    <h2><%= @user.name %> Profile</h2>
    <% if @user == current_user %>
      <p><%= link_to 'Edit profile', edit_user_path(@user) %></p>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-auto">
      <p><%= link_to 'Create Event', new_event_path, class: "form-button text-center" %></p>
      <%= image_tag user_avatar(@user), class: 'img-fluid', alt: "#{@user.name} photo" %>
    </div>
    <div class="col">
      <% if @user.events.any? %>
        <section id="schedule" class="section-with-bg">
          <div class="container" data-aos="fade-up">
              <h3>Your Events Schedule</h3>
            <div class="tab-content row justify-content-center" data-aos="fade-up" data-aos-delay="200">
              <%= render partial: 'events/event', collection: @user.events %>
            </div>
          </div>
        </section>
      <% else %>
        <h3 class="buffer-top"><%= @user.name %> has not yet created an event</h3>
      <% end %>
    </div>
  </div>
</div>