config/routes.rb
Rails.application.routes.draw do
  resources :photos
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "events#index"
    devise_for :users

    resources :preferences, only: [:update]
    resources :events do
      resources :comments, only: [:create, :destroy]
      resources :subscriptions, only: [:create, :destroy]
      resources :photos, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update]
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
  has_many :photos

  validates :title, presence: true, length: { maximum: 255 }
  validates :address, :datetime, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # Встроенный в девайз фильтр - посылает незалогиненного пользователя
  before_action :authenticate_user!, except: [:show, :index]

  # Задаем объект @event для экшена show
  before_action :set_event, only: [:show]

  # Задаем объект @event от текущего юзера для других действий
  before_action :set_current_user_event, only: [:edit, :update, :destroy]

  def index
    @events = Event.where('datetime > ?', Time.current)
    @next_event = Event.where('datetime > ?', Time.current).order(datetime: :asc).first
  end

  def show
    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    # Болванка модели для формы добавления фотографии
    @new_photo = @event.photos.build(params[:photo])
  end

  def new
    @event = current_user.events.build
  end

  def edit
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      # Используем сообщение из файла локалей ru.yml
      # controllers -> events -> created
      redirect_to @event, notice: I18n.t('controllers.events.created')
    else
      flash[:alert] = "Please, fill the form"
      render :new
      flash.discard
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: I18n.t('controllers.events.updated')
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to current_user, notice: I18n.t('controllers.events.destroyed')
  end

  private

  def set_current_user_event
    @event = current_user.events.find(params[:id])
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description)
  end
end

app/views/events/_event.html.erb
<div class="row schedule-item">
  <div class="col-md-4">
    <p><%= l event.datetime, format: :long %></p>
  </div>
  <div class="col-md-6">
    <div class="speaker">
      <%#= image_tag 'speakers/1.jpg', alt:'Brenden Legros' %>
    </div>
    <h4><%= link_to event.title, event_path(event) %><span> | <%= event.address %></span></h4>
    <p><%= event.description  %></p>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_with model: @event do |f| %>
  <div class="mb-3">
    <%= f.label :title, class: "form-label" %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :address, class: "form-label" %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :datetime, class: "form-label" %>
    <%= f.datetime_field :datetime, type:"datetime-local", class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :description, class: "form-label" %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="d-grid gap-2 col-6 mx-auto">
    <%= f.submit 'Save', class: 'form-button' %>
  </div>
<% end %>
</br>
<div class="details"><%= button_to 'Delete', @event, method: :delete,
                                   onclick: "return confirmDestroy('Are you sure?')",
                                   class: "btn btn-outline-danger" %>
</div>

app/views/events/edit.html.erb
<% content_for :title do %>Edit Event: <%= @event.title %>
<% end %>
<div class="container px-4 p-5">
  <div class="row text-center">
    <div class="col gx-0"></div>
    <div class="col-md-6">
      <div class="section-header">
        <h2>Editing Event</h2>
        <%= link_to 'Back', @event %>
      </div>
      <%= render 'form' %></br>
    </div>
    <div class="col"></div>
  </div>
</div>

app/views/events/index.html.erb
<!-- ======= Hero Section ======= -->
<section id="hero">
  <div class="hero-container" data-aos="zoom-in" data-aos-delay="100">
    <h1 class="mb-4 pb-0">The Annual<br><span>Party</span> Friends</h1>
    <p class="mb-4 pb-0">Don’t miss this event in your life</p>
    <a href="https://www.youtube.com/watch?v=kM_GaNPtGwg" class="glightbox play-btn mb-4"></a>
    <a href="#about" class="about-btn scrollto">About The Event</a>
  </div>
</section><!-- End Hero Section -->

<main id="main">

  <!-- ======= About Section ======= -->
  <section id="about">
    <div class="container" data-aos="fade-up">
      <div class="row">
        <div class="col-lg-6">
          <h2>Next Event</h2>
          <% if @next_event.blank? %>
            <p>No found events...</p>
          <% else %>
          <p><%= @next_event.title %></p>
          <% end %>
        </div>
        <div class="col-lg-3">
          <h3>Where</h3>
          <% if @next_event.blank? %>
            <p>No found addresses...</p>
          <% else %>
          <p><%= @next_event.address %></p>
          <% end %>
        </div>
        <div class="col-lg-3">
          <h3>When</h3>
          <% if @next_event.blank? %>
            <p>No found time...</p>
          <% else %>
          <p><%= l @next_event.datetime, format: :short %></p>
          <% end %>
        </div>
      </div>
    </div>
  </section><!-- End About Section -->

  <!-- ======= Schedule Section ======= -->
  <section id="schedule" class="section-with-bg">
    <div class="container" data-aos="fade-up">
      <div class="section-header">
        <h2>Event Schedule</h2>
        <p>Here is our event schedule</p>
      </div>
      <div class="tab-content row justify-content-center" data-aos="fade-up" data-aos-delay="200">
        <%= render partial: 'events/event', collection: @events %>
      </div>
        </div>
  </section><!-- End Schedule Section -->


  <!-- ======= Friends Section ======= -->
  <section id="speakers">
    <div class="container" data-aos="fade-up">
      <div class="section-header">
        <h2>Event Friends</h2>
        <p>Here are some of our party</p>
      </div>

      <div class="row">
        <div class="col-lg-4 col-md-6">
          <div class="speaker" data-aos="fade-up" data-aos-delay="100">
            <%= image_tag 'speakers/1.jpg', alt:'Speaker 1', class:'img-fluid' %>
            <div class="details">
              <h3><a href="speaker-details.html">Brenden Legros</a></h3>
              <p>Quas alias incidunt</p>
              <div class="social">
                <a href=""><i class="bi bi-twitter"></i></a>
                <a href=""><i class="bi bi-facebook"></i></a>
                <a href=""><i class="bi bi-instagram"></i></a>
                <a href=""><i class="bi bi-linkedin"></i></a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6">
          <div class="speaker" data-aos="fade-up" data-aos-delay="200">
            <%= image_tag 'speakers/2.jpg', alt:'Speaker 2', class:'img-fluid' %>
            <div class="details">
              <h3><a href="speaker-details.html">Hubert Hirthe</a></h3>
              <p>Consequuntur odio aut</p>
              <div class="social">
                <a href=""><i class="bi bi-twitter"></i></a>
                <a href=""><i class="bi bi-facebook"></i></a>
                <a href=""><i class="bi bi-instagram"></i></a>
                <a href=""><i class="bi bi-linkedin"></i></a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6">
          <div class="speaker" data-aos="fade-up" data-aos-delay="300">
            <%= image_tag 'speakers/3.jpg', alt:'Speaker 3', class:'img-fluid' %>
            <div class="details">
              <h3><a href="speaker-details.html">Cole Emmerich</a></h3>
              <p>Fugiat laborum et</p>
              <div class="social">
                <a href=""><i class="bi bi-twitter"></i></a>
                <a href=""><i class="bi bi-facebook"></i></a>
                <a href=""><i class="bi bi-instagram"></i></a>
                <a href=""><i class="bi bi-linkedin"></i></a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6">
          <div class="speaker" data-aos="fade-up" data-aos-delay="100">
            <%= image_tag 'speakers/4.jpg', alt:'Speaker 4', class:'img-fluid' %>
            <div class="details">
              <h3><a href="speaker-details.html">Jack Christiansen</a></h3>
              <p>Debitis iure vero</p>
              <div class="social">
                <a href=""><i class="bi bi-twitter"></i></a>
                <a href=""><i class="bi bi-facebook"></i></a>
                <a href=""><i class="bi bi-instagram"></i></a>
                <a href=""><i class="bi bi-linkedin"></i></a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6">
          <div class="speaker" data-aos="fade-up" data-aos-delay="200">
            <%= image_tag 'speakers/5.jpg', alt:'Speaker 5', class:'img-fluid' %>
            <div class="details">
              <h3><a href="speaker-details.html">Alejandrin Littel</a></h3>
              <p>Qui molestiae natus</p>
              <div class="social">
                <a href=""><i class="bi bi-twitter"></i></a>
                <a href=""><i class="bi bi-facebook"></i></a>
                <a href=""><i class="bi bi-instagram"></i></a>
                <a href=""><i class="bi bi-linkedin"></i></a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6">
          <div class="speaker" data-aos="fade-up" data-aos-delay="300">
            <%= image_tag 'speakers/6.jpg', alt:'Speaker 6', class:'img-fluid' %>
            <div class="details">
              <h3><a href="speaker-details.html">Willow Trantow</a></h3>
              <p>Non autem dicta</p>
              <div class="social">
                <a href=""><i class="bi bi-twitter"></i></a>
                <a href=""><i class="bi bi-facebook"></i></a>
                <a href=""><i class="bi bi-instagram"></i></a>
                <a href=""><i class="bi bi-linkedin"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </section><!-- End Speakers Section -->

  <!-- ======= Venue Section ======= -->
  <section id="venue">

    <div class="container-fluid" data-aos="fade-up">

      <div class="section-header">
        <h2>Event Venue</h2>
        <p>Event venue location info and gallery</p>
      </div>

      <div class="row g-0">
        <div class="col-lg-6 venue-map">
          <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>

        <div class="col-lg-6 venue-info">
          <div class="row justify-content-center">
            <div class="col-11 col-lg-8 position-relative">
              <h3><% if @next_event.blank? %>
                  <p>No found events...</p>
                <% else %>
                  <%= @next_event.title %>
                <% end %></h3>
              <p>A party is usually the best place to have some drinks. It's more than just getting wasted and making out with random strangers too - it's drinking responsibly and having a good time without getting drunk-dialed.</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid venue-gallery-container" data-aos="fade-up" data-aos-delay="100">
      <div class="row g-0">
        <div class="col-lg-3 col-md-4">
          <div class="venue-gallery">
            <%= link_to image_tag('gallery/1.jpg', class:"img-fluid"),
                        path_to_image('gallery/1.jpg'), class:'glightbox',
                        data: {gall:"venue-gallery"} %>
          </div>
        </div>

        <div class="col-lg-3 col-md-4">
          <div class="venue-gallery">
            <%= link_to image_tag('gallery/2.jpg', class:"img-fluid"),
                        path_to_image('gallery/2.jpg'), class:'glightbox',
                        data: {gall:"venue-gallery"} %>
          </div>
        </div>

        <div class="col-lg-3 col-md-4">
          <div class="venue-gallery">
            <%= link_to image_tag('gallery/3.jpg', class:"img-fluid"),
                        path_to_image('gallery/3.jpg'), class:'glightbox',
                        data: {gall:"venue-gallery"} %>
          </div>
        </div>

        <div class="col-lg-3 col-md-4">
          <div class="venue-gallery">
            <%= link_to image_tag('gallery/4.jpg', class:"img-fluid"),
                        path_to_image('gallery/4.jpg'), class:'glightbox',
                        data: {gall:"venue-gallery"} %>
        </div>
        </div>

        <div class="col-lg-3 col-md-4">
          <div class="venue-gallery">
            <%= link_to image_tag('gallery/5.jpg', class:"img-fluid"),
                        path_to_image('gallery/5.jpg'), class:'glightbox',
                        data: {gall:"venue-gallery"} %>
          </div>
        </div>

        <div class="col-lg-3 col-md-4">
          <div class="venue-gallery">
            <%= link_to image_tag('gallery/6.jpg', class:"img-fluid"),
                        path_to_image('gallery/6.jpg'), class:'glightbox',
                        data: {gall:"venue-gallery"} %>
          </div>
        </div>

        <div class="col-lg-3 col-md-4">
          <div class="venue-gallery">
            <%= link_to image_tag('gallery/7.jpg', class:"img-fluid"),
                        path_to_image('gallery/7.jpg'), class:'glightbox',
                        data: {gall:"venue-gallery"} %>
          </div>
        </div>

        <div class="col-lg-3 col-md-4">
          <div class="venue-gallery">
            <%= link_to image_tag('gallery/8.jpg', class:"img-fluid"),
                        path_to_image('gallery/8.jpg'), class:'glightbox',
                        data: {gall:"venue-gallery"} %>
          </div>
        </div>

      </div>
    </div>

  </section><!-- End Venue Section -->


  <!-- =======  F.A.Q Section ======= -->
  <section id="faq">

    <div class="container" data-aos="fade-up">

      <div class="section-header">
        <h2>F.A.Q </h2>
      </div>

      <div class="row justify-content-center" data-aos="fade-up" data-aos-delay="100">
        <div class="col-lg-9">

          <ul class="faq-list">

            <li>
              <div data-bs-toggle="collapse" class="collapsed question" href="#faq1">It will be fun? <i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
              <div id="faq1" class="collapse" data-bs-parent=".faq-list">
                <p>
                  Are you kidding? Of course!
                </p>
              </div>
            </li>

            <li>
              <div data-bs-toggle="collapse" href="#faq2" class="collapsed question">Can I bring drinks? <i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
              <div id="faq2" class="collapse" data-bs-parent=".faq-list">
                <p>
                  Sure, I know you have a lot of beer
                </p>
              </div>
            </li>

            <li>
              <div data-bs-toggle="collapse" href="#faq3" class="collapsed question">Do I have a limit for spend money? <i class="bi bi-chevron-down icon-show"></i><i class="bi bi-chevron-up icon-close"></i></div>
              <div id="faq3" class="collapse" data-bs-parent=".faq-list">
                <p>
                  Absolutely no!
                </p>
              </div>
            </li>
          </ul>

        </div>
      </div>

    </div>

  </section><!-- End  F.A.Q Section -->

  <!-- ======= Subscribe Section ======= -->
  <section id="subscribe">
    <div class="container" data-aos="zoom-in">
      <div class="section-header">
        <h2>Newsletter</h2>
        <p>Rerum numquam illum recusandae quia mollitia consequatur.</p>
      </div>

      <form method="POST" action="#">
        <div class="row justify-content-center">
          <div class="col-lg-6 col-md-10 d-flex">
            <input type="text" class="form-control" placeholder="Enter your Email">
            <button type="submit" class="ms-2">Subscribe</button>
          </div>
        </div>
      </form>

    </div>
  </section><!-- End Subscribe Section -->
</main><!-- End #main -->

app/views/events/new.html.erb
<div class="container px-4 p-5 text-center">
  <div class="section-header">
    <h2>Create Event</h2>
    <%= link_to 'Back', current_user %>
  </div>
  <div class="row">
    <div class="col"></div>
    <div class="col-md-8">
      <%= render 'form' %>
    </div>
    <div class="col"></div>
  </div>
</div>

app/views/events/show.html.erb
<% content_for :title do %>Event - <%= @event.title %>
<% end %>
<section id="speakers-details">
  <div class="container">
    <div class="section-header text-center">
      <h2><%= @event.title %></h2>
      <% if current_user_can_edit?(@event) %>
        <%= link_to 'Edit event', edit_event_path(@event) %>
      <% end %>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= image_tag event_photo(@event), class: 'img-fluid', alt: "#{@event.title}" %>
        <div class="d-flex flex-row mb-3">
          <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="container">
          <h3>When: <%= l @event.datetime, format: :long %></h3>
          <h3>Decription: <%= @event.description %></h3>
          <h3>Address: <small><%= link_to @event.address,
                                          "https://yandex.ru/maps/?text=#{@event.address}" %></small></h3>
          <h4>Organizer: <%= link_to @event.user.name, @event.user %></h4>
          <% if current_user_can_edit?(@event) %>
            <%= render partial: 'photos/form', locals: { photo: @new_photo || @event.photos.build } %>
          <% end %>
          <div class="row justify-content-start">
            <% if @event.subscriptions.except(@new_subscription).any? %>
              <h4>Come:</h4>
              <%= render partial: 'subscriptions/subscription',
                         collection: @event.subscriptions.except(@new_subscription) %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <br>
    <div class="container text-center">
      <div class="row">
        <% if current_user_can_edit?(@event) %>
          <div class="col gx-0"></div>
          <div class="col-md-6">
            <h4>Leave a comment:</h4>
            <%= render partial: 'comments/form',
                       locals: { comment: @new_comment || @event.comments.build } %>
          </div>
          <div class="col gx-0"></div>
        <% else %>
          <div class="col-md-6">
            <br>
            <h4>Are you go?</h4>
            <%= render partial: 'subscriptions/form', locals: {
              subscription: @new_subscription || @event.subscriptions.build
            } %>
        </div>
        <div class="col-md-6">
          <br>
          <h4>Leave a comment:</h4>
          <%= render partial: 'comments/form',
                     locals: { comment: @new_comment || @event.comments.build } %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <%= render partial: 'comments/comment',
                 collection: @event.comments.except(@new_comment) %>
    </div>
  </div>
</section>